### ISSUE TITLE
Problems with Cloudflare analytics engine Clickhouse after upgrading to 3.0.0

### ISSUE THREAD

**Issue by spelexander** [Altinity/clickhouse-grafana#558] opened 2024-05-12 16:48 UTC
I use Cloudflare Analytics Engine and Grafana cloud. In the official documentation for Cloudflare Analytics Engine, using this plugin is the recommended option for integrating with Grafana. 

I have been using Altinity plugin with Grafana for some time, but due to the Angular deprecation warnings I decided to upgrade today.

Since upgrading my plugin to 3.0.0 I have been unable to:
- Edit query settings (e.g. to select a database, table or DateTime column)
<img width="1772" alt="Screenshot 2024-05-12 at 6 47 49 pm" src="https://github.com/Altinity/clickhouse-grafana/assets/26774216/ad2dc2e7-a036-473c-9d9c-680c1d845c0b">
- Edit the plugin configuration in Grafana settings
<img width="666" alt="Screenshot 2024-05-12 at 6 55 12 pm" src="https://github.com/Altinity/clickhouse-grafana/assets/26774216/71a2b12a-19b3-4288-9093-a942d881a180">

### Steps to reproduce:
1. Follow the setup guide here: https://developers.cloudflare.com/analytics/analytics-engine/grafana/
2. Create a new datasource
3. You will be unable to Save and Test the datasource without a crash in Grafana

### Error message:
```
An unexpected error happened
Details
TypeError: Cannot assign to read only property 'dataSourceUrl' of object '#<Object>'

    at https://renewview.grafana.net/public/plugins/vertamedia-clickhouse-datasource/module.js?_cache=3.0.0:2:3699851
    at div
    at vt (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/Connections.a1ad302de305309a8646.js:48:2348)
    at o (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:1:172)
    at form
    at Pt (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/Connections.a1ad302de305309a8646.js:56:1914)
    at At (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/Connections.a1ad302de305309a8646.js:56:1464)
    at f (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:239:18087)
    at div
    at div
    at div
    at div
    at te (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:902:4503)
    at d (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:63:30037)
    at c
    at div
    at K (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:239:22026)
    at wt (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/Connections.a1ad302de305309a8646.js:56:4946)
    at Bt (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/Connections.a1ad302de305309a8646.js:56:5358)
    at j (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:29171)
    at j (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:31348)
    at Gt (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/Connections.a1ad302de305309a8646.js:64:2099)
    at Suspense
    at l (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:63:125457)
    at er (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:184:11347)
    at j (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:29171)
    at co (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1035:4448)
    at lr (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1035:11997)
    at Nt (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:17387)
    at j (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:31348)
    at main
    at div
    at div
    at div
    at kn (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:184:2441)
    at div
    at kr (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:184:6891)
    at co (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1035:4448)
    at lr (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1035:11997)
    at hs (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1035:11333)
    at fr (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:17686)
    at j (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1044:25387)
    at v (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:111:8970)
    at _ (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1377:112624)
    at c (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:479:21361)
    at l (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:63:125457)
    at g (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:63:125966)
    at et (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/330.3e128f9f2fef2b8f895b.js:1016:530)
    at Ll (https://grafana-assets.grafana.net/grafana/11.1.0-70648/public/build/2540.a40dde18ed1e1774799b.js:195:127)
```

**Comment by Slach** [comment] 2024-05-13 06:33
duplicated https://github.com/Altinity/clickhouse-grafana/issues/516
3.1.0 was submitted on friday
let's wait review

**Comment by caglarsayin** [comment] 2024-05-16 10:22
I cannot believe how long it takes

**Comment by Slach** [comment] 2024-05-16 11:44
@caglarsayin 3.1.0 was released recently, please check it

**Comment by dangeredwolf** [comment] 2024-10-19 16:24
Same issue on 3.2.3

**Comment by Slach** [comment] 2024-10-19 20:47
@dangeredwolf which `grafana-server` version do you use?

**Comment by dangeredwolf** [comment] 2024-10-19 20:49
@Slach I'm using Grafana Cloud, version  11.4.0-77383

**Comment by Slach** [comment] 2024-10-19 20:52
@dangeredwolf is this self-hosted open-source version of grafana?

When you said "same"
do you mean you see in console
`TypeError: Cannot assign to read only property 'dataSourceUrl' of object '#<Object>'` ? 

or just "save & test" doesn't work?

**Comment by dangeredwolf** [comment] 2024-10-19 20:56
I had the issue where the settings was broken with `TypeError: Cannot assign to read only property 'dataSourceUrl' of object '#<Object>'` (I found this GitHub issue by googling the error), and I also have the issue where I cannot set the timestamp column. Though now it's letting me access the settings without crashing this time.

**Comment by dangeredwolf** [comment] 2024-10-19 20:59
I am also using Cloudflare Analytics Engine and I am unable to set the `timestamp` column as the timestamp. In fact, it does not list any databases, tables, or columns.

<img width="754" alt="Screenshot 2024-10-19 at 13 57 42" src="https://github.com/user-attachments/assets/66d2fb8d-78aa-45a5-92b5-9e8a1a80d2bc">
<img width="684" alt="Screenshot 2024-10-19 at 13 57 34" src="https://github.com/user-attachments/assets/6f354efe-2556-47da-a07c-3f7a8b5e9df1">

I can get the data to properly display in Grafana, but I cannot filter it by an time range because I have been unable to set the timestamp column.

**Comment by Slach** [comment] 2024-10-20 16:02
Ok. let's try to figure out

could you share
```
curl -vvv -X POST "https://api.cloudflare.com/client/v4/accounts/<your-account-id>/analytics_engine/sql" -H "Authorization: Bearer <your-api-token>" --data "SELECT version()"
```
without sensitive credentials

**Comment by dangeredwolf** [comment] 2024-10-20 16:14
I ran it and

```
< HTTP/2 422 
...
* Connection #0 to host api.cloudflare.com left intact
Input was invalid: unknown function call: version
```

Huh... So there's that.

**Comment by Slach** [comment] 2024-10-20 16:21
sorry, try Version() instead version()

**Comment by Slach** [comment] 2024-10-20 16:24
ok. 
try
```
curl -vvv -X POST "https://api.cloudflare.com/client/v4/accounts/<your-account-id>/analytics_engine/sql" -H "Authorization: Bearer <your-api-token>" --data "SHOW CREATE TABLE system.columns"
```

**Comment by dangeredwolf** [comment] 2024-10-20 16:27
`unknown function call: Version`

`unsupported SQL statement type: SHOW CREATE TABLE system.columns`

🫠

**Comment by Slach** [comment] 2024-10-20 16:56
last check 

same parameters but different --data

`--data "SELECT name,database,table,type FROM system.columns WHERE type LIKE '%Date%' OR type LIKE '%DateTime%' OR type = 'UInt32' ORDER BY type,name FORMAT JSON"`

**Comment by dangeredwolf** [comment] 2024-10-20 18:01
`unsupported binary operator: LIKE`

Sorry if these outputs aren't more helpful, seems Cloudflare's SQL API is a bit limited :/ 

[Even though ironically Cloudflare still recommends this specific plugin for use with Analytics Engine](https://developers.cloudflare.com/analytics/analytics-engine/grafana/#grafana-plugin-setup)

**Comment by Slach** [comment] 2024-10-20 19:36
check
`--data "SELECT name,database,table,type FROM system.columns WHERE substring(type,1,4) = 'Date' OR type = 'UInt32' ORDER BY type,name FORMAT JSON"`

looks like they tested on 2.x

**Comment by dangeredwolf** [comment] 2024-10-21 16:55
`cannot specify a database when selecting a dataset: system`

**Comment by Slach** [comment] 2024-10-22 08:00
hm, looks like cloudflare workers analytics engine have too many restrictions

**Comment by Slach** [comment] 2024-10-22 08:07
did you try just setup database and table and time related column, manually in UI, instead of try to select it from drop down?

**Comment by dangeredwolf** [comment] 2024-10-22 15:28
> did you try just setup database and table and time related column, manually in UI, instead of try to select it from drop down?

By manually in the UI do you mean typing it in and hitting enter? Cause if so, I did try that but Grafana won’t let me. If I’m missing something else though or if there’s a configuration file that I can manually edit I’d love to know about it

**Comment by Slach** [comment] 2024-10-24 09:44
@dangeredwolf are you sure do you use latest version of plugin?
i just tried manual typing and just press enter  in grafana cloud and everything works as expected.
![image](https://github.com/user-attachments/assets/72d6b421-b11f-4882-9c17-0cc64f096079)

**Comment by dangeredwolf** [comment] 2024-10-24 11:47
@Slach 3.2.3 is the latest version, right?
<img width="966" alt="Screenshot 2024-10-24 at 04 46 40" src="https://github.com/user-attachments/assets/9268d2bc-1bbc-4bce-bb13-4c58e9de05a9">

**Comment by Slach** [comment] 2024-10-24 11:49
yes, i created data source 
after that i succesfully add panel

could you save screencast to reproduce whats failed on your side?

**Comment by dangeredwolf** [comment] 2024-10-24 12:13
I am able to add it but am unable to set Database or Columns in the UI even though I can write SQL queries to do so
https://github.com/user-attachments/assets/8ba5332b-d056-42ab-8aef-61588a9ff55a

If I could somehow manually force `timestamp` as the timestamp column in the configuration somewhere it might be possible to work around this, but I'm not sure how to do that.

**Closed** 2024-10-25 11:40 UTC
